"""add ticker symbol to quotes table

Revision ID: 224f7192ea22
Revises: 310a305c5e24
Create Date: 2016-10-12 08:55:47.785171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224f7192ea22'
down_revision = '310a305c5e24'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('ticker', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'ticker')
    ### end Alembic commands ###
