"""add ticker symbol to trades table

Revision ID: 310a305c5e24
Revises: 6558cb32d4c8
Create Date: 2016-10-12 08:49:36.373242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310a305c5e24'
down_revision = '6558cb32d4c8'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('ticker', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'ticker')
    ### end Alembic commands ###
