"""create time column

Revision ID: 6558cb32d4c8
Revises: 917f1b076a74
Create Date: 2016-10-10 21:08:17.873321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6558cb32d4c8'
down_revision = '917f1b076a74'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.add_column('trades', sa.Column('time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'time')
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('capital', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'account_pkey')
    )
    ### end Alembic commands ###
